# {{PROJECT_NAME}} — Project Overview

Generated by /init from template. Edit values in memory/config.override.json or re-run /init.

**Version:** 1.0.0
**Last Updated:** {{LAST_UPDATED}}
**Generated by:** init

---

## Project Identity

| Field | Value |
|-------|-------|
| Project Name | {{PROJECT_NAME}} |
| Type | {{PROJECT_TYPE}} |
| Target Platform | {{TARGET_PLATFORM}} |
| Primary Language | {{PRIMARY_LANGUAGE}} |
| Framework | {{PRIMARY_FRAMEWORK}} |
| Team Size | {{TEAM_SIZE}} |

---

## Purpose
{{PROJECT_PURPOSE}}

## Target Users
- Primary: {{PRIMARY_USER}}
- Secondary: {{SECONDARY_USER}}
- Use Case: {{CORE_USE_CASE}}

---

## Business Context
- Before: {{BEFORE_STATE}}
- After: {{AFTER_STATE}}

### Success Metrics
- {{METRIC_1}}
- {{METRIC_2}}
- {{METRIC_3}}

---

## Tech Stack
| Layer | Technology | Version |
|-------|------------|---------|
| Language | {{PRIMARY_LANGUAGE}} | {{LANG_VERSION}} |
| Framework | {{PRIMARY_FRAMEWORK}} | {{FRAMEWORK_VERSION}} |
| State Management | {{STATE_MGMT}} | {{STATE_MGMT_VERSION}} |
| DI | {{DI_LIB}} | {{DI_VERSION}} |
| Networking | {{HTTP_LIB}} | {{HTTP_LIB_VERSION}} |
| Local DB | {{LOCAL_DB}} | {{LOCAL_DB_VERSION}} |
| Routing | {{ROUTING_LIB}} | {{ROUTING_VERSION}} |

---

## Architecture Pattern
{{ARCHITECTURE_PATTERN}}

{{FOLDER_STRUCTURE}}

---

## Core Features
{{CORE_FEATURES}}

---

## Development Commands
{{CMD_SETUP}}
{{CMD_CODEGEN}}
{{CMD_LINT}}
{{CMD_TEST}}
{{CMD_BUILD}}

---

## Performance Targets
| Metric | Target |
|--------|--------|
| {{PERF_METRIC_1}} | {{PERF_TARGET_1}} |
| {{PERF_METRIC_2}} | {{PERF_TARGET_2}} |

---

## Known Technical Debt
- {{TECH_DEBT_1}}
- {{TECH_DEBT_2}}

---

## Team & Contacts
- Tech Lead: {{TECH_LEAD}}
- QA Lead: {{QA_LEAD}}
- Product Owner: {{PRODUCT_OWNER}}

---

## References
- Architecture Guide: memory/ARCHITECTURE.md
- Definition of Done: memory/DOD.md
- Code Style: memory/CODE_STYLE.md
- Testing Strategy: memory/TESTING_STRATEGY.md